export const genreMap = {
  all: "All",
  fantasy: "Fantasy",
  science: "Science Fiction",
  dystopian: "Dystopian",
  action: "Action and Adventure",
  mystery: "mystery",
  horror: "Horror",
  thriller: "Thriller and Suspense",
  historical: "Historical Fiction",
  romance: "Romance",
  women: "Women's Fiction",
  comtemporary: "Contemporary Fiction",
  literary: "Literary Fiction",
  magical: "Magical Realism",
  graphic: "Graphic Novel",
  short: "Short Story",
  young: "Young Adult",
  new: "New Adult",
  children: "Children's",
  memoir: "Memoir & Autobiograpy",
  biography: "Biography",
  food: "Food & Drink",
  art: "Art & Photography",
  self: "Self-Help",
  history: "History",
  travel: "Travel",
  crime: "True Crime",
  hummor: "Hummor",
  essay: "Essays",
  tech: "Science & Technology",
};
